# Generated by Django 5.2.3 on 2025-06-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='novost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый пост', max_length=75, verbose_name='Название')),
                ('intro', models.CharField(default='Текст анонса', max_length=250, verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Пост')),
                ('date', models.DateField(verbose_name='Дата публикации поста')),
            ],
        ),
    ]
