# Generated by Django 5.2.3 on 2025-07-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novost',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='novost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/post_images/'),
        ),
    ]
